spin_manifest_version = 2

[application]
authors = ["Shivay Lamba <shivaylamba@gmail.com>"]
description = "A Serverless AI application written in Python and deployed to Fermyon Cloud"
name = "sentiment-analysis"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "sentiment-analysis"

[component.sentiment-analysis]
source = "app.wasm"
ai_models = ["llama2-chat"]
[component.sentiment-analysis.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
